-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageReadConfirmations/db/page_read_confirmations_requests.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_read_confirmations_requests (
  prcr_revision INTEGER UNSIGNED NOT NULL,
  prcr_page INTEGER UNSIGNED NOT NULL,
  prcr_wiki_id VARCHAR(255) NOT NULL,
  prcr_timestamp BLOB DEFAULT NULL,
  PRIMARY KEY(
    prcr_revision, prcr_page, prcr_wiki_id
  )
);
