-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageReadConfirmations/db/page_read_confirmations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_read_confirmations (
  prc_user INT UNSIGNED NOT NULL,
  prc_rev INT UNSIGNED NOT NULL,
  prc_wiki_id VARCHAR(255) NOT NULL,
  prc_page INT UNSIGNED NOT NULL,
  prc_read_at BINARY(14) DEFAULT NULL,
  PRIMARY KEY(prc_user, prc_rev, prc_wiki_id)
) /*$wgDBTableOptions*/;
