-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageReadConfirmations/db/page_read_confirmations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE page_read_confirmations (
  prc_user INT NOT NULL,
  prc_rev INT NOT NULL,
  prc_wiki_id VARCHAR(255) NOT NULL,
  prc_page INT NOT NULL,
  prc_read_at TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(prc_user, prc_rev, prc_wiki_id)
);
