-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageReadConfirmations/db/page_read_confirmations_assignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE page_read_confirmations_assignments (
  prca_key VARCHAR(255) NOT NULL,
  prca_type VARCHAR(255) NOT NULL,
  prca_page INT NOT NULL,
  prca_wiki_id VARCHAR(255) NOT NULL,
  prca_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(
    prca_page, prca_key, prca_type, prca_wiki_id
  )
);
